name: Sylvain
favicon: null
layout_spectrum: 0.18117592064663768
typography_spectrum: 0.6577825364656746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5891455847304314
  lightness: 0.5723444048780948
  saturation: 0.5681466236710548
  rhythmicContrast: 0.8869032354559749
purpose: []
